name: CI

env:
  SVDTOOLS_VERSION: 0.2.3
  SVD2RUST_VERSION: 0.24.0

on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Done
        run: exit 0

  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - stm32f0
          - stm32f1
          - stm32f2
          - stm32f3
          - stm32f4
          - stm32f7
          - stm32h7
          - stm32l0
          - stm32l1
          - stm32l4
          - stm32l5
          - stm32g0
          - stm32g4
          - stm32mp1
          - stm32wl
          - stm32wb

    env:
      CRATES: ${{ matrix.crate }}
      CARGO_INCREMENTAL: 0
      SVDTOOLS: svdtools

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils

      - name: Create working crate
        run: make crates

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ${{ matrix.crate }}

      - name: Install tools
        run: |
          curl -L https://github.com/burrbull/svdtools/releases/download/Unreleased/svdtools-x86_64-unknown-linux-gnu.gz | gzip -d - > ~/.cargo/bin/svdtools && chmod +x ~/.cargo/bin/svdtools
          curl -L https://github.com/rust-embedded/svd2rust/releases/download/v$SVD2RUST_VERSION/svd2rust-x86_64-unknown-linux-gnu.gz | gzip -d - > ~/.cargo/bin/svd2rust && chmod +x ~/.cargo/bin/svd2rust

      - name: Patch SVDs
        run: make -j2 patch

      - name: Check SVDs
        run: make lint

      - name: Build PACs
        run: make -j2 svd2rust

      - name: Check PACs
        run: make -j2 check
