name: CI

on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crate:
          - stm32f0
          - stm32f1
          - stm32f2
          - stm32f3
          - stm32f4
          - stm32f7
          - stm32h7
          - stm32l0
          - stm32l1
          - stm32l4
          - stm32l5
          - stm32g0
          - stm32g4
          - stm32mp1
          - stm32wl
          - stm32wb
    env:
      CRATES: ${{ matrix.crate }}
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
      - name: Install svd2rust
        uses: actions-rs/install@v0.1
        with:
          crate: svd2rust
          version: 0.20.0
          use-tool-cache: true
      - name: Install svdtools
        uses: actions-rs/install@v0.1
        with:
          crate: svdtools
          version: 0.1.0
          use-tool-cache: true
      - name: Put new cargo binary directory into path
        run: echo "~/cargo-bin" >> $GITHUB_PATH
      - name: Patch SVDs
        run: SVDTOOLS=svdtools make -j2 patch
      - name: Build PACs
        run: SVDTOOLS=svdtools make -j2 svd2rust
      - name: Check PACs
        run: SVDTOOLS=svdtools make -j2 check
