name: CI

env:
  SVDTOOLS_VERSION: 0.2.0
  SVD2RUST_VERSION: 0.21.0

on:
  push:
    branches: [ staging, trying, master, bors/staging, bors/trying ]
  pull_request:

jobs:
  install-deps:
    name: Install svdtools & svd2rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - name: Add fictive crate
        run: |
          cargo init

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
        with:
          sharedKey: prebuilded-svdtools-${{ env.SVDTOOLS_VERSION }}-svd2rust-${{ env.SVD2RUST_VERSION }}

      - name: Install tools
        run: |
          cargo install svdtools --version $SVDTOOLS_VERSION --target-dir deps-target
          cargo install svd2rust --version $SVD2RUST_VERSION --target-dir deps-target
          rm -rf deps-target

      - name: Install dependencies
        run: |
          echo 'bare-metal = "1.0.0"' >> Cargo.toml
          echo 'vcell = "0.1.3"' >> Cargo.toml
          echo 'cortex-m = "0.7.2"' >> Cargo.toml
          echo 'cortex-m-rt = "0.7.1"' >> Cargo.toml
          cargo check

  check:
    name: Check
    runs-on: ubuntu-latest
    needs: [install-deps]
    strategy:
      matrix:
        crate:
          - stm32f0
          - stm32f1
          - stm32f2
          - stm32f3
          - stm32f4
          - stm32f7
          - stm32h7
          - stm32l0
          - stm32l1
          - stm32l4
          - stm32l5
          - stm32g0
          - stm32g4
          - stm32mp1
          - stm32wl
          - stm32wb

    env:
      CRATES: ${{ matrix.crate }}
      CARGO_INCREMENTAL: 0
      SVDTOOLS: svdtools

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt

      - name: Add fictive crate
        run: |
          cargo init

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
        with:
          sharedKey: prebuilded-svdtools-${{ env.SVDTOOLS_VERSION }}-svd2rust-${{ env.SVD2RUST_VERSION }}

      - name: Patch SVDs
        run: make -j2 patch

      - name: Build PACs
        run: make -j2 svd2rust

      - name: Check PACs
        run: make -j2 check
